CREATE TABLE MEMBER
(
  ID    VARCHAR2(30 BYTE) NOT NULL,
  PW    VARCHAR2(10 BYTE) NOT NULL,
  NICKNAME  VARCHAR2(20 BYTE) NOT NULL
)
TABLESPACE TS_KYTCOOK
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MEMBER_ID_PK ON MEMBER
(ID)
LOGGING
TABLESPACE TS_KYTCOOK
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MEMBER ADD (
  CONSTRAINT MEMBER_ID_PK
  PRIMARY KEY
  (ID)
  USING INDEX MEMBER_ID_PK
  ENABLE VALIDATE);