ALTER TABLE SCOTT.MKADDRTB
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.MKADDRTB CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.MKADDRTB
(
  ID            NUMBER(3)                       NOT NULL,
  NAME          VARCHAR2(30 BYTE),
  ADDRESS       VARCHAR2(200 BYTE),
  TELEPHONE     VARCHAR2(30 BYTE),
  GENDER        VARCHAR2(10 BYTE),
  RELATIONSHIP  VARCHAR2(500 BYTE),
  BIRTHDAY      VARCHAR2(30 BYTE),
  COMMENTS      VARCHAR2(500 BYTE),
  REGISTEDATE   VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCOTT.MKADDRTBK_PK ON SCOTT.MKADDRTB
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SCOTT.MKADDRTB ADD (
  CONSTRAINT MKADDRTBK_PK
  PRIMARY KEY
  (ID)
  USING INDEX SCOTT.MKADDRTBK_PK
  ENABLE VALIDATE);