CREATE TABLE SCOTT.ZIPCODE_T
(
  UID_NO    NUMBER,
  ZIPCODE   NUMBER(6)                           NOT NULL,
  ZDO       VARCHAR2(30 BYTE)                   NOT NULL,
  SIGU      VARCHAR2(30 BYTE)                   NOT NULL,
  DONG      VARCHAR2(30 BYTE),
  RI        VARCHAR2(30 BYTE),
  BUNGI     VARCHAR2(30 BYTE),
  APTNAME   VARCHAR2(50 BYTE),
  UPD_DATE  VARCHAR2(30 BYTE),
  ADDRESS   VARCHAR2(200 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          6M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
?
?
CREATE UNIQUE INDEX SCOTT.ZIPCODE_UIDNO_PK ON SCOTT.ZIPCODE_T
(UID_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          960K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
?
?
ALTER TABLE SCOTT.ZIPCODE_T ADD (
  CONSTRAINT ZIPCODE_UIDNO_PK
  PRIMARY KEY
  (UID_NO)
  USING INDEX SCOTT.ZIPCODE_UIDNO_PK
  ENABLE VALIDATE);