ALTER TABLE SCOTT.MEMO
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.MEMO CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.MEMO
(
  NO            NUMBER(5),
  FROM_ID       VARCHAR2(10 BYTE)               NOT NULL,
  TO_ID         VARCHAR2(10 BYTE)               NOT NULL,
  MEMO_CONTENT  VARCHAR2(4000 BYTE),
  CREATE_DATE   VARCHAR2(30 BYTE),
  READ_YN       VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCOTT.MEMO_NO_PK ON SCOTT.MEMO
(NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


MEMO 