CREATE TABLE SCOTT.BOARD_SUB_T
(
  B_FILE   VARCHAR2(100 BYTE),
  BS_SIZE  NUMBER(9,2),
  BS_SEQ   NUMBER(5)                            NOT NULL,
  B_NO     NUMBER(5)                            NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCOTT.XPKBOARD_SUB_T ON SCOTT.BOARD_SUB_T
(BS_SEQ, B_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;