ALTER TABLE SCOTT.KHBOARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.KHBOARD CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.KHBOARD
(
  ID       NUMBER(5),
  TITLE    VARCHAR2(100 BYTE),
  WRITER   VARCHAR2(30 BYTE),
  CONTENT  VARCHAR2(4000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCOTT.KHBOARD_ID_PK ON SCOTT.KHBOARD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SCOTT.KHBOARD ADD (
  CONSTRAINT KHBOARD_ID_PK
  PRIMARY KEY
  (ID)
  USING INDEX SCOTT.KHBOARD_ID_PK
  ENABLE VALIDATE);